[package]
name = "veda-search-query"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.10", features = ["full"] }
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"
serde_json = "1.0"

v_api = { git = "https://github.com/semantic-machines/v-common-api.git", branch = "main" }
v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
v_module = { git = "https://github.com/semantic-machines/v-common-module.git" }
v_authorization = "0.1.0"
v_az_lmdb = { git = "https://github.com/semantic-machines/v-common-az-lmdb.git" }
v_search = { git = "https://github.com/semantic-machines/v-common-search.git" }
