[package]
name = "veda-mstorage"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"
serde_json = "1.0"
chrono = "0.4"

v_queue = "0.1"
v_authorization = "0.1.0"

v_api = { git = "https://github.com/semantic-machines/v-common-api.git", branch = "main" }
v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
v_storage = { git = "https://github.com/semantic-machines/v-common-storage.git", version = "0.1.1" }
v_module = { git = "https://github.com/semantic-machines/v-common-module.git", version = "0.1.3" }
v_az_lmdb = { git = "https://github.com/semantic-machines/v-common-az-lmdb.git" }
