[package]
name = "veda-tools"
version = "0.1.0"
authors = ["Itiua <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
time = "0.1"
log = "0.4.13"
rust-ini = "0.16.0"
nng = "0.5.1"
serde_json = "1.0.61"
serde = "1.0.119"
url = "2.2.0"
quote = "1.0.8"
type-cli = "0.0.3"

v_authorization = "0.1.0"
v_queue = "0.1.2"
v_onto = { package = "v-common-onto", version = "0.1.1" }
v_api = { package = "v-common-api", version = "0.1.2" }
v_az_lmdb = { package = "v-common-az-lmdb", version = "0.1.1" }
v_search = { package = "v-common-search", version = "0.1.2" }
v_module = { package = "v-common-module", version = "0.1.7" }
v_ft_xapian = { package = "v-common-ft-xapian", version = "0.1.5" }
