[package]
name = "veda-ft-query"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"
serde_json = "1.0"

v_api = { git = "https://github.com/semantic-machines/v-common-api.git", branch = "main" }
v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
v_module = { git = "https://github.com/semantic-machines/v-common-module.git", version = "0.1.2" }
v_search = { git = "https://github.com/semantic-machines/v-common-search.git" }
v_ft_xapian = { git = "https://github.com/semantic-machines/v-common-ft-xapian.git", version = "0.1.1" }
v_storage = { git = "https://github.com/semantic-machines/v-common-storage.git", version = "0.1.1" }

