[package]
name = "veda-winpak"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-winpak"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
time = "0.1.42"
serde_json = "1.0"
log = "0.4"
futures = "0.1"
tokio = "0.1"
tokio-current-thread = "0.1.6"
tiberius = {version="0.3.2", default-features=false,features=["chrono"]}
futures-state-stream = "0.1"
voca_rs = "1.8.0"

v_queue = "0.1"

v_api = { git = "https://github.com/semantic-machines/v-common-api.git", branch = "main" }
v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
v_search = { git = "https://github.com/semantic-machines/v-common-search.git" }
v_storage = { git = "https://github.com/semantic-machines/v-common-storage.git" }
v_module = { git = "https://github.com/semantic-machines/v-common-module.git" }
