[package]
name = "veda-search-index-tt"
version = "0.1.0"
authors = ["Roman Karpov <roman.karpov@gmail.com>"]
edition = "2018"

[dependencies]
clickhouse-rs = {git = "https://github.com/xbinxu/clickhouse-rs", rev = "6950ce586050d97cb423c9d49f142e54416cd46f", default-features = false, features = ["async_std"] }
futures = "0.3.5"
log = "0.4"
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "1.4.0"
regex = "1"
url = "2.1.1"
bincode = "1.2.1"
serde = "1.0.104"
v_queue = "0.1"

v_api = { git = "https://github.com/semantic-machines/v-common-api.git", branch = "main" }
v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
v_search = { git = "https://github.com/semantic-machines/v-common-search.git" }
v_storage = { git = "https://github.com/semantic-machines/v-common-storage.git", version = "0.1.1" }
v_module = { git = "https://github.com/semantic-machines/v-common-module.git", version = "0.1.2" }
