[package]
name = "veda-fanout-email"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
lettre = "0.9"
lettre_email = "0.9"

v_queue = "=0.1"
v_onto = { package = "v-common-onto", version = "=0.1.1" }
v_api = { package = "v-common-api", version = "=0.1.2" }
v_storage = { package = "v-common-storage", version = "=0.1.5" }
v_search = { package = "v-common-search", version = "=0.1.2" }
v_module = { package = "v-common-module", version = "=0.1.13" }
