[package]
name = "veda-scripts-v8"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
lazy_static = "1.4.0"
rust_decimal = "1.7.0"

# sudo apt install libglib2.0-dev
rusty_v8 = "0.15.0"

v_queue = "0.1"
v_onto = { package = "v-common-onto", version = "0.1.1" }
v_api = { package = "v-common-api", version = "0.1.2" }
v_storage = { package = "v-common-storage", version = "0.1.2" }
v_search = { package = "v-common-search", version = "0.1.2" }
v_module = { package = "v-common-module", version = "0.1.5" }
v_ft_xapian = { package = "v-common-ft-xapian", version = "0.1.3" }
v_v8 = { package = "v-common-v8", version = "0.1.3" }
