[package]
name = "veda-scripts-v8"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
lazy_static = "1.4.0"
rust_decimal = "1.7.0"

# sudo apt install libglib2.0-dev
rusty_v8 = "0.15.0"

v_queue = "0.1"

v_api = { git = "https://github.com/semantic-machines/v-common-api.git", branch = "main" }
v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
v_v8 = { git = "https://github.com/semantic-machines/v-common-v8.git", version = "0.1.1" }
v_module = { git = "https://github.com/semantic-machines/v-common-module.git", version = "0.1.1" }
v_storage = { git = "https://github.com/semantic-machines/v-common-storage.git" }
v_search = { git = "https://github.com/semantic-machines/v-common-search.git" }
v_ft_xapian = { git = "https://github.com/semantic-machines/v-common-ft-xapian.git", version = "0.1.1" }
