[package]
name = "veda-ro-storage"
version = "0.1.0"
authors = ["Itiua <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"

v_onto = { package = "v-common-onto", version = "0.1.1" }
v_storage = { package = "v-common-storage", version = "0.1.2" }
v_module = { package = "v-common-module", version = "0.1.5" }
